{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "000b5955_21b28f25",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000682
      },
      "writtenOn": "2022-06-28T21:11:04Z",
      "side": 1,
      "message": "Looks correct to me. How do you find this error?\n\nIs there somewhere else where we have this issue?",
      "revId": "18e3fb5443dacd87a849e258b86567f1da606a25",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}