{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "949fa76d_4355130c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 1000350
      },
      "writtenOn": "2023-02-21T09:33:26Z",
      "side": 1,
      "message": "CI failure is not related to this commit",
      "revId": "6c2a9acbd62b54617a8230665be1e79192884715",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}