{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "ee7f017a_341cd2df",
        "filename": "http/ut/utility_test.cpp",
        "patchSetId": 1
      },
      "lineNbr": 92,
      "author": {
        "id": 1000153
      },
      "writtenOn": "2022-01-11T18:52:55Z",
      "side": 1,
      "message": "@Nan, can you please take a look at this condition.  I believe it\u0027s related to your change.  If you comment the next line in, it throws an exception.",
      "range": {
        "startLine": 92,
        "startChar": 4,
        "endLine": 92,
        "endChar": 46
      },
      "revId": "ef84edd1416bb3558672e02a9930049956412952",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}